# Generated by Django 5.2.17 on 2026-08-31 12:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('SCHEDULING', 'Scheduling'), ('SELECTING_SHOP', 'Selecting Shop'), ('FINALIZED', 'Finalized')], default='SCHEDULING', max_length=20)),
                ('total_issued_participant_links', models.PositiveIntegerField(default=0)),
                ('total_revoked_participant_links', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_candidate_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gathering.candidatedate')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatherings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidatedate',
            name='gathering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_dates', to='gathering.gathering'),
        ),
        migrations.CreateModel(
            name='ParticipantLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('rate_limited_once', models.BooleanField(default=False)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='gathering.gathering')),
            ],
            options={
                'ordering': ['issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOING', 'Going'), ('MAYBE', 'Maybe'), ('NOT_GOING', 'Not Going')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_responses', to='gathering.candidatedate')),
                ('participant_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_responses', to='gathering.participantlink')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant_link', 'candidate_date'), name='one_schedule_response_per_link_and_date')],
            },
        ),
    ]
