# Generated by Django 5.2.17 on 2026-09-03 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='finalized_shop_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='voting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShopVoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_shop_ids', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('participant_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_vote_submission', to='gathering.participantlink')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField()),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_shops', to='gathering.gathering')),
            ],
            options={
                'ordering': ['added_at'],
                'constraints': [models.UniqueConstraint(fields=('gathering', 'shop_id'), name='one_shortlisted_row_per_gathering_and_shop')],
            },
        ),
    ]
